language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
#  - '7.1'
#  - 'nightly'
  
env:
  - NETTE_VERSION='~2.0'
  
matrix:
  include:
#    - php: 5.6
#      env: NETTE_VERSION=2.3
#    - php: 5.6
#      env: NETTE_VERSION=2.2
#    - php: 5.6
#      env: NETTE_VERSION='~2.1'
#    - php: 5.6
#      env: NETTE_VERSION='~2.2'
#    - php: 5.6
#      env: NETTE_VERSION=2.3
#    - php: 5.6
#      env: NETTE_VERSION='~2.4'
      
before_install:
  - composer require "nette/caching:${NETTE_VERSION}" --no-update
  - composer require "nette/di:${NETTE_VERSION}" --no-update
  - composer require "nette/neon:${NETTE_VERSION}" --no-update

install: composer update --prefer-source --no-interaction --dev

before_script:
    - phpenv config-rm xdebug.ini || true