  
language: php   
php: 
- 5.4
- 5.5
- 5.6
- 7.0
- nightly
env: 
- NETTE_VERSION=2.2
- NETTE_VERSION=2.3
- NETTE_VERSION=2.4

matrix:
  exclude:      
    env: NETTE_VERSION=2.4
    - php: 5.4
    - php: 5.5
    
before_install:
  - composer require "nette/caching:${NETTE_VERSION}" --no-update
  - composer require "nette/di:${NETTE_VERSION}" --no-update
  - composer require "nette/neon:${NETTE_VERSION}" --no-update

install: composer update --prefer-source --no-interaction --dev

before_script:
    - phpenv config-rm xdebug.ini || true