  
language: php   
php: 
- 5.4
- 5.5
- 5.6
- 7.0
- nightly
env: 
- NETTE_VERSION=2.2
- NETTE_VERSION=2.3
- NETTE_VERSION=2.4

matrix:
  exclude:      
  - php: 5.4
    env: NETTE_VERSION=2.4
  - php: 5.5
    env: NETTE_VERSION=2.4
    
before_install:
  - composer require "nette/nette:${NETTE_VERSION}" --no-update

install: composer update --prefer-source --no-interaction --dev

before_script:
    - phpenv config-rm xdebug.ini || true
    # Install Apache
#    - sudo apt-get update -qq
#    - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl > /dev/null
#    - sudo chmod 777 -R /home/travis/build/redCOMPONENT-COM/redSHOP/
#    - sudo ln -s /home/travis/build/redCOMPONENT-COM/redSHOP/tests/system/joomla-cms/ /var/www/joomla-cms #Add     joomla to apache htdocs
#    - sudo sed -i -e "s,AllowOverride[ ]None,AllowOverride All,g" /etc/apache2/sites-available/default
#    - sudo /etc/init.d/apache2 restart
#    - composer install --dev --prefer-dist

#    # XVFB
#    - "export DISPLAY=:99.0"
#    - "Xvfb :99.0 -extension RANDR > /dev/null &"
#
#    # Window manager
#    - echo "c10"
#    - "sudo apt-get install fluxbox -y --force-yes"
#    - echo "c11"
#    - "fluxbox &"
#
#    # Selenium server
#    - "wget http://selenium-release.storage.googleapis.com/2.41/selenium-server-standalone-2.41.0.jar"
#    - "java -jar selenium-server-standalone-2.41.0.jar > /dev/null 2>/dev/null &"
#    - sleep 30 # gives enough time to Selenium to start


script:
#    - php .travis/traviswebserverckecker.php http://localhost/joomla-cms/installation/index.php # Test apache
#    - mv tests/acceptance.suite.dist.yml tests/acceptance.suite.yml # Create travis system tests config file
#    - "wget http://codeception.com/codecept.phar"
#    - php ./codecept.phar build
#    - php ./codecept.phar run
    - ./vendor/codeception/codeception/codecept/run